### ISSUE TITLE
Jiggler menu does not appear

### ISSUE THREAD

**Issue by rgreinho** [bhaller/Jiggler#1]
With Jiggler 1.7, the application goes to the status bar, but the menu does not appear when clicking on the icon, making it impossible to disable it or adjusting the options.

I'm using OS X 10.11.5 and Jiggler installed with brew.

**Comment by bhaller** [comment]
Well that’s… odd.  Nobody else has reported this bug, and it’s working great for me on my own 10.11.5 machines.  I would suggest the usual things like reboot, uninstall/reinstall (I have no idea what “brew” is, but you can install Jiggler simply by downloading it from http://www.sticksoftware.com/software/Jiggler.html and dragging it to your Applications folder, so you might want to do that rather than run the risk that a nonstandard install procedure has messed things up), etc.  If that doesn’t help, then I would have to suspect a bad interaction with some other piece of software running on your machine; you might see if Jiggler works when run in a guest account that does not have other software extensions enabled.  You could also check Console.app to see if there are any relevant error logs there; if there are, post them here.  Apart from these suggestions, there's not really much I can do from my end to debug this issue, as far as I can see.  If you come up with more information on this problem, let me know.

**Comment by rgreinho** [comment]
I followed your advice and it worked, Thanks!

**Comment by bhaller** [comment]
Ah, perfect.  Thanks for letting me know.

Cheers,
-B.
