### ISSUE TITLE
on 10.14.6 Jiggler does not believe I did Turn on accessibility

### ISSUE THREAD

**Issue by smurp** [bhaller/Jiggler#15]
I have clicked the checkbox beside Jiggler.app in `Security & Privacy > Privacy` but whenever I try to start Jiggler it asks me to "Turn on accessibility" again.

This is Jiggler 1.8

Thoughts?

**Comment by bhaller** [comment]
Perhaps the checkbox did not remain checked, for some reason?  Or perhaps you have two copies of Jiggler installed accidentally, and you gave permissions to one while you are actually running the other?  Perhaps you are trying to run Jiggler out of the disk image, rather than installing it in your Applications folder, and that is causing issues with the accessibility registration?  Perhaps there's an OS X issue and you need to reboot?  That's all I can think of.  But the accessibility mechanisms are controlled by OS X; Jiggler has no control over how that stuff works, and so it can't be a bug in Jiggler itself.  It just uses the system calls that Mac OS provides.  So I'm going to close this issue; if you can't get it to work, this would be an issue to take up with Apple, since it would be their bug.  Good luck!

**Comment by smurp** [comment]
I think the issue had something to do with a rogue process which was filling the disk. Thanks!
