### ISSUE TITLE
New Feature: Jiggle in place (no mouse migration)

### ISSUE THREAD

**Issue by willemrosenthal** [bhaller/Jiggler#31]
Right now, the mouse can jiggle itself into a sleep corner or away to some place a click should not occur. Can we add a feature where the jiggle remembers the mouse's starting coordinates so that it can giggle randomly, but return to its starting position, preventing a random migration across the screen?

**Comment by bhaller** [comment]
Actually, it does this already.  It doesn't return to *exactly* the same location, because that wouldn't work to keep some software awake (if it checks, say, once a minute to see if the mouse location has changed).  But it will keep itself confined within a fairly small area.  It won't end up in a sleep corner unless you left the cursor pretty close to that corner already.
