### ISSUE TITLE
MacOS Mojave

### ISSUE THREAD

**Issue by inferno-adam** [bhaller/Jiggler#6]
Jiggler doesn't work with MacOS Mojave.

**Comment by bhaller** [comment]
Hi!  For the record, you later emailed: "Hello! I’m trying to get Jiggler 1.7 working on the MacOS Mojave 10.4 beta and it doesn’t work… the mouse never moves. Is there something I can try to get it to work? Thanks!"  OK, so.  I'm not on Mojave yet, and can't be for some time, unfortunately.  I also have no idea why this would no longer work.  If you happen to be an OS X developer, I'd be happy to accept a pull request that fixes this issue, otherwise this may take me a while (months, at least) to address.  Sorry!

**Comment by ahenriksen11** [comment]
Thanks for getting back to me. It turns out that after I upgraded to Mojave that Jiggler was no longer authorized to control the system. I dig through the Control Panel and security settings and found where to allow it. I’m on the road so I don’t know offhand where it’s at. 

Kind Regards,

Adam Henriksen

On Aug 13, 2018, at 7:25 PM, Ben Haller <notifications@github.com> wrote:

Hi! For the record, you later emailed: "Hello! I’m trying to get Jiggler 1.7 working on the MacOS Mojave 10.4 beta and it doesn’t work… the mouse never moves. Is there something I can try to get it to work? Thanks!" OK, so. I'm not on Mojave yet, and can't be for some time, unfortunately. I also have no idea why this would no longer work. If you happen to be an OS X developer, I'd be happy to accept a pull request that fixes this issue, otherwise this may take me a while (months, at least) to address. Sorry!

**Comment by ahenriksen11** [comment]
Yes, it needs to request access for control in System Preferences -> Security & Privacy -> Accessibility. Other apps I have, request access to control the system. JIggler did not do this when I launched it. Here’s the link to Apple Support and a screen shot below.

 

https://support.apple.com/kb/PH25774?viewlocale=en_US&locale=en_US

 

 

Kind Regards,

Adam Henriksen
480- 455-7999 Cell

**Comment by bhaller** [comment]
OK, good stuff, thanks.  Once I'm on Mojave, this will at least give me an idea of where to start.  BTW, I get that it fails to move the mouse, but that mean that it actually fails to keep the machine awake?  Jiggler makes other system calls that *ought* to keep the machine awake even if the mouse doesn't move...

**Comment by ahenriksen11** [comment]
No problem! Yes, it fails to keep the machine awake.

 

Kind Regards,

Adam Henriksen
480- 455-7999 Cell

**Comment by TychoSchenkeveld** [comment]
Would be great if this could be fixed :)

**Comment by bhaller** [comment]
@TychoSchenkeveld once you grant it permission there, does it work?  I.e. not only jiggle the mouse, but actually keep the machine awake as a result?  Another user above reported that their machine still fell asleep, if I understood correctly.  Anyway, I'm not on Mojave yet, and probably won't be for a while, sorry; if any other Mac developer wants to fix this and submit a pull request, I'd be happy to accept it.  I only have my one laptop, and I can't upgrade it right now...

**Comment by ahenriksen11** [comment]
In my case, after upgrading to Mojave, Jiggler was not enabled in the Security & Privacy control panel options. Once I checked the box, everything worked again. @TychoSchenkeveld , you can try unchecking the box and then re-check it to see if it can re-apply the permissions.

**Comment by TychoSchenkeveld** [comment]
Yes exactly, the box was unchecked for me too. I just referenced the picture for others to find it more easily.

Once I checked it it works just fine, keeping the machine awake as normal.

**Comment by joeabill** [comment]
I'm having an issue where Jiggler isn't showing up as an app under Accessibility and I am unable to add it to the list either. Because of this it seems Jiggler isn't working for me.

**Comment by bhaller** [comment]
> I'm having an issue where Jiggler isn't showing up as an app under Accessibility and I am unable to add it to the list either. Because of this it seems Jiggler isn't working for me.

Well, I have no idea why that would happen.  Reboot?  Reinstall Jiggler?  Reinstall macOS?  What does and doesn't show up under Accessibility is Apple's territory; I have no idea how to fix such an issue.

**Comment by Giographically** [comment]
ready for strangeness?  Two Macs, an iMac Pro and a 2016 MacBook Pro.  Both fully updated Mojave.  Same energy settings in MacOS.  Same Jiggler preferences.  iMac Pro has two additional screens fyi, if that's somehow contributing (I doubt it)...  Since I got the iMac pro, Jiggler has never worked.  The app installs, I can select it in the security pane, but it actually just doesn't do anything while running.  Also strangely the "Timed Quit" function is greyed out.   Not at all the same on my MacBook Pro.  Jiggler functions perfectly normally like it always has.  Timed Quit is not greyed out.   What in the world.

**Comment by Giographically** [comment]
I cannot believe it.  I'm the biggest tool.  I never saw that there was an Enable Jiggler option. Literally the first option, one my eye skipped over because I guess I assumed that with the app open I wanted it on!  Carry on, Jiggler is up and jiggling.

**Comment by dttocs** [comment]
> I'm having an issue where Jiggler isn't showing up as an app under Accessibility and I am unable to add it to the list either. Because of this it seems Jiggler isn't working for me.

This worked for me when Jiggler didn't show up in the Accessibility list automatically:

1. open your Applications folder 
2. Open Preferences -> Security & Privacy -> Accessibility
3. (If needed, unlock accessibility changes by clicking the lock in the lower-left corner and entering an admin username and password)
4.  Drag the Jiggler icon from Applications into the "Allow the apps below to control your computer" list.

**Comment by Giographically** [comment]
I'm a 100% moron.  The solution to my issue was clicking the very first check box to enable Jiggler.  Then timed quit worked, duh! Thanks for your help though!

**Comment by joeabill** [comment]
Just wanted to report back that I got my issue resolved. Apparently, virus scan was blocking it.

**Comment by mcjohnalds** [comment]
Tested working on osx 10.14.4.

**Comment by profrgm** [comment]
Have read all the comments above and am scratching my head, as Jiggler has worked perfectly on all the Mac OS versions I have used since the Jiggler app was first introduced. Currently using Mac OS 10.14.6.

**Comment by bhaller** [comment]
This is fixed in Jiggler 1.8, just released.
